### ISSUE TITLE
Feature request: plot the ontology

### ISSUE THREAD

**Issue by richelbilderbeek** [joshwlambert/DAISIEmainland#11]
Dear DAISIEmainland maintainer,

Thanks for DAISIEmainland and its many plotting functions!

The plotting function that is missing however, is one to plot the ontology of species, i.e. that produces pictures such as this:

![Screenshot from 2021-11-01 10-29-40](https://user-images.githubusercontent.com/2098230/139651474-fa73ca75-510e-4667-bb33-d6255d858752.png)

I know it is a hard problem to produce beautiful plots, yet from the thoroughness of DAISIEmainland I predict attempts at plotting this has been made. If I am correct, I predict this functionality has been removed as it did not always results in beautiful plots. If so, I'd prefer to be able to see 'ugly' plot over nothing at all, maybe even from a different package (`DAISIEmainlandplot` seems a pretty name to me :-) ).

What is the status and what are the plans for this plotting functionality?

**Comment by joshwlambert** [comment]
Thank you for the idea of having these scenarios be made with a plotting functions in R. The picture pasted above is made using Tikz (latex). I have not attempted to write a plotting function for these in the past, and the I feel the pay-off of having them be produced in R is not worth the time input required to write what I believe would be a substantial amount of code.

**Comment by richelbilderbeek** [comment]
Thanks for the clear answer!

Would you mind to have some experimental plotting added if I do it? It will not be clean and it can well be non-`exported`, it is just that I could use it.

**Comment by joshwlambert** [comment]
Feel free to write some plotting code, if you feel that the code is useful for the package once it is finished please make a pull request and if I agree it is useful it can be kept on the package. 😄

**Comment by richelbilderbeek** [comment]
Done!

Here is my favorite test:

```r
test_that("interesting picture, with recolonisation", {
  set.seed(
    9,
    kind = "Mersenne-Twister",
    normal.kind = "Inversion",
    sample.kind = "Rejection"
  )
  mainland <- sim_mainland(
    total_time = 10,
    m = 10,
    mainland_ex = 1.0
  )

  # Clade goes extinct, but after island age
  mainland_clade <- mainland[[1]]
  plot_mainland_clade(mainland_clade)
  
  island <- sim_island(
    total_time = 1,
    island_pars = c(1, 1, 10, 12, 1),
    mainland = mainland_clade,
    mainland_sample_prob = 1,
    mainland_sample_type = "complete")
  plot_island(island)
})
```

The mainland clade:

![Screenshot from 2021-12-05 21-11-30](https://user-images.githubusercontent.com/2098230/144762285-b5ecaf9e-7b70-4e77-a997-701f2f5e9302.png)

The island:

![Screenshot from 2021-12-05 21-11-43](https://user-images.githubusercontent.com/2098230/144762296-3216a5c5-88f0-4975-92d2-1e44331e1019.png)

**Comment by richelbilderbeek** [comment]
I am happy the pictures visualize all the info produced by `sim_mainland` and `sim_island`. Sure, they can be made more intuitive, but I need a closer look for that. Still, it is helpful that all information is visualized :-)

**Comment by joshwlambert** [comment]
Thanks for the new plotting functions. Can this issue be closed once the new code reaches main?

**Comment by richelbilderbeek** [comment]
Thanks for accepting! Sure, this Issue can be closed when it reaches `main`, or now :-)
