### ISSUE TITLE
Suggest: add supplemenary materials as PDF

### ISSUE THREAD

**Issue by richelbilderbeek** [joshwlambert/DAISIEmainland#14]
Dear DAISIEmainland maintainer.

Thanks for DAISIEmainland and its excellent article-in-preparation. Especially the supplementary materials, with the 43 scenarios are useful for the package. 

Could these (i.e. the PDF pages that describe the 43 scenarios) already (i.e. before publication) be added to the package, e.g. in `inst/extdata`?

Would be awesome and allow me/users to use scenario's in their questions :-)

**Comment by joshwlambert** [comment]
Resolved, will be closed when merged to main
