### ISSUE TITLE
Suggest: show the resulting errors in the vignette

### ISSUE THREAD

**Issue by richelbilderbeek** [joshwlambert/DAISIEmainland#18]
Dear DAISIEmainland maintainer,

Thanks for DAISIEmainland and having a vignette to demonstrate what it does for a relatively simple parameter set.

Unexpectedly, in the end, when the inference error is calculated (see vignette code below) ...

    ```{r Calculate error}
    errors <- DAISIEmainland::calc_error(
      daisie_data = island,
      ideal_ml = ideal_ml,
      empirical_ml = empirical_ml)
    ```

... the resulting errors are not displayed on screen, nor interpreted.

I suggest to show the resulting errors and give an intepretation. Sure, maybe the seed needs to be changed to a more interesting-yet-simple scenario :-)

**Comment by joshwlambert** [comment]
Issue finished, will close when merged to main.
