### ISSUE TITLE
Feature request: sim_island_with_mainland for t = 0

### ISSUE THREAD

**Issue by richelbilderbeek** [joshwlambert/DAISIEmainland#19]
Dear DAISIEmainland maintainer,

Thanks for DAISIEmainland and its many tests to ensure its correctness! It is great to see that all input variables and their constraints are checked early in the calculation!

I feel however, that one constraint can be loosened: the minimal simulation time. When using `sim_island_with_mainland`, the `total_time` must be bigger than zero. However, I feel it makes sense to create the data without anything happening.

In code, I suggest this test to pass:

```r
test_that("sim_island_with_mainland with 0.0 time", {
  expect_silent(
    sim_island_with_mainland(
      total_time = 0.0, # Nothing happened yet
      m = 2, # Irrelevant
      island_pars = c(1, 1, 10, 0.1, 1), # Irrelevant
      mainland_ex = 1, # Irrelevant
      mainland_sample_prob = 1, # Irrelevant
      mainland_sample_type = "undiscovered", # Irrelevant
      replicates = 1 # Irrelevant
    )
  )
})
```

I already checked that if I changed `testit::assert(total_time > 0)` to `testit::assert(total_time >= 0)`, the code just runs fine and the tests pass.

I hope you'll loose up this constraint, so empty islands and mainlands can be created. Or, to prevent me writing the code below :-) :

```
sim_island_with_mainland(
  total_time = 0.0000000000000001, # Looks silly! Sure, .Machine$double.xmin looks cooler :-)
  # ...
)
```

**Comment by joshwlambert** [comment]
@richelbilderbeek Thanks for the work on this issue already, I have used the test you wrote to make sure the code is working as expected.

**Comment by joshwlambert** [comment]
Finished issue, will close when merged to main.
