### ISSUE TITLE
Suggest: export `sim_mainland`

### ISSUE THREAD

**Issue by richelbilderbeek** [joshwlambert/DAISIEmainland#21]
Dear DAISIEmainland maintainer,

Thanks for `DAISIEmainland` and its broad range of functionality it provides.

I developed a simple function called `plot_mainland` (which I'll put in a Pull Request to develop soon) to plot the simulated mainland clades. Its documentation looks like this:

```r
#' mainland <- DAISIEmainland:::sim_mainland(
#'   # ... 
#' )
#'
#' plot_mainland(mainland)
```

Note the use of the triple colons `:::` when calling `sim_mainland`, as `sim_mainland` is not an exported function.

I suggest to export `sim_mainland` to make that documentation prettier. Or, when reasoned from another perspective: I suggest to export `sim_mainland` as it is apparently important enough to make it into the documentation.

And hey, I'd be happy to do so myself in a Pull Request :-)

**Comment by joshwlambert** [comment]
Sorted, will close when merged to main.
