### ISSUE TITLE
stac 1 and stac 4 identical?

### ISSUE THREAD

**Issue by richelbilderbeek** [joshwlambert/DAISIEmainland#25]
Dear DAISIEmainland maintainers,

Thanks for DAISIEmainland and its fine documention!

When I take a look at the `sim_island_with_mainland` documentation, however, ...

```
?sim_island_with_mainland
```

I see that the descriptions for stac == 1 and stac == 4 are identical (both are `Non_endemic_MaxAge`):

![Screenshot from 2021-11-29 17-58-59](https://user-images.githubusercontent.com/2098230/143910662-b3f51c72-bc5f-41c9-84c8-b550a65f7d2a.png)

I assume there is a difference and that the documentation had just a copy-paste error.

I hope it will be fixed so that the doc of DAISIEmainland is even awesomer!

**Comment by joshwlambert** [comment]
Thanks for picking up on this mistake. The correct documentation should say: stac 4: Non_endemic. Feel free to change this on your branch.

**Comment by richelbilderbeek** [comment]
Done! Issue will be closed when merged to main :-)
