### ISSUE TITLE
Example in plot_ideal_island does not run

### ISSUE THREAD

**Issue by joshwlambert** [joshwlambert/DAISIEmainland#28]
The example returns  Error in (function (stac)  : Invalid event with value 0 Tip: values can be 1, 2, 3, 4, 5 or 6.

**Comment by richelbilderbeek** [comment]
Yup, you are right. Will fix now :-)

**Comment by richelbilderbeek** [comment]
Should be fixed now, awaiting the results of the build ...

**Comment by richelbilderbeek** [comment]
Will be fixed when merged to master :-)

**Comment by richelbilderbeek** [comment]
I guess it did not close when merged to master. Closing by hand now :-)
