### ISSUE TITLE
purr and tidyverse

### ISSUE THREAD

**Issue by joshwlambert** [joshwlambert/DAISIEmainland#29]
Currently purrr is called but not stated as a dependency. Also, I am not a fan of having tidyverse dependencies (exception being ggplot2), please only use when necessary over using base R functions.

**Comment by richelbilderbeek** [comment]
I struggled with this decision rule:

>  only use when necessary over using base R functions.

What define 'when necessary'?

In any case, I will create two helper functions (in `test_utils.R`) to replace my calls to `purrr` to get rid of the dependency :-)

**Comment by richelbilderbeek** [comment]
Dependency on `purrr` is removed. This Issue will be closed when merged to master.
