### ISSUE TITLE
Function housekeeping

### ISSUE THREAD

**Issue by joshwlambert** [joshwlambert/DAISIEmainland#30]
It's create to have *_to_* functions to help convert between things in a readable way. Please move all of these functions into a file called sim_utils. A plot_utils file already exists so if any of them are exclusively used for plotting please put them in plot_utils instead. If they are not used for in the simulation or plotting, but rather the testing, please create a file called test_utils and put them there.

**Comment by richelbilderbeek** [comment]
Will do :+1:

**Comment by richelbilderbeek** [comment]
Done! Issue will be closed when merged to master :+1:
