### ISSUE TITLE
Write official DAISIE data standard documentation

### ISSUE THREAD

**Issue by joshwlambert** [joshwlambert/DAISIEmainland#38]

**Comment by richelbilderbeek** [comment]
I think an overview in the main `DAISIEmainland::DAISIEmainland` doc would be the best place for that. I volunteer to do all the island structures :-)

**Comment by joshwlambert** [comment]
I have tried writing up the data standards in DAISIEmainland::DAISIEmainland but I feel it is better suited to a vignette.

**Comment by joshwlambert** [comment]
@richelbilderbeek do you think all data structures should have the suffix *_data?

**Comment by richelbilderbeek** [comment]
> I have tried writing up the data standards in DAISIEmainland::DAISIEmainland but I feel it is better suited to a vignette.

Cool, looking forward to see it!

> @richelbilderbeek do you think all data structures should have the suffix *_data?

I feel that, usually, `data` is redundant or inexpressive. As an exampke, in English we usually speak about colonisation history or community ontology, instead of colonisation data. 

As always, feel free to ignore :-)

**Comment by joshwlambert** [comment]
@richelbilderbeek thanks for the tips, I decided to keep the data suffix as for some it gave clarity and I use it for all for consistency. Let me know if you're happy with the naming and I will start changing the names currently used in the package. See #5cc1708 on standards branch.

**Comment by richelbilderbeek** [comment]
Nice! 

I've taken a look at the vignette, I feel it is a good start!

I see the use of the `multi_`prefix when using `_data` as a suffix, as the singular of `_data` equals the plural `_data`, and `_datas` is not exactly English. However, for `_clade`, English has the plural `_clades`. Well, I guess you prefer `multi_` for consistency, so having said that, I think these are good conventions :-)
