### ISSUE TITLE
Create plot with phylogenies for mainland

### ISSUE THREAD

**Issue by richelbilderbeek** [joshwlambert/DAISIEmainland#40]

**Comment by richelbilderbeek** [comment]
Getting there, time to draw the vertical lines as well :-)

![Screenshot from 2021-12-25 14-41-19](https://user-images.githubusercontent.com/2098230/147386207-e4306560-89af-4b92-80c2-047d8c3968cf.png)

**Comment by richelbilderbeek** [comment]
Note the error where y > 1.0

**Comment by richelbilderbeek** [comment]
Yay, vertical lines!

![Screenshot from 2021-12-25 15-02-39](https://user-images.githubusercontent.com/2098230/147386637-51895067-54d5-4338-af12-e4cfd4a9dd57.png)

**Comment by richelbilderbeek** [comment]
Limited y in [0, 1], looks good:

![Screenshot from 2021-12-25 15-19-21](https://user-images.githubusercontent.com/2098230/147386977-8d173d9a-fde3-4296-a851-412b2eda50f0.png)

**Comment by richelbilderbeek** [comment]
Works, but not for multiple clades yet:

![Screenshot from 2021-12-25 15-25-25](https://user-images.githubusercontent.com/2098230/147387075-bf209d1a-52e0-486e-b268-0395bd38b4ab.png)

**Comment by richelbilderbeek** [comment]
Long live the unique species ID!

![Screenshot from 2021-12-25 15-29-46](https://user-images.githubusercontent.com/2098230/147387166-f724fa0f-6f00-4ab9-baa5-7fbcc6e75d21.png)

**Comment by joshwlambert** [comment]
The mainland plot looks great! Can we now delete the mainland_plot branch?

**Comment by richelbilderbeek** [comment]
Yup, I think we safely can. If you have any precious code there, go ahead and save it, before deleting that branch :+1:

**Comment by joshwlambert** [comment]
Great, mainland_plot branch has been deleted.
