### ISSUE TITLE
Create `plot_daisie_data`

### ISSUE THREAD

**Issue by richelbilderbeek** [joshwlambert/DAISIEmainland#42]
~~Currently, we can plot the mainland and the island, i.e. data types `mainland` and `island`. However, the `daisie_data` cannot be plotted yet, which would be useful to verify the `format_to_daisie_data` function works nice.~~

It is easy to get a `daisy_data` from a `daisie_mainland_data`:

```
  daisie_mainland_data <- sim_island_with_mainland(
    total_time = 1,
    m = 10,
    island_pars = c(1, 1, 10, 0.1, 1),
    mainland_ex = 1,
    mainland_sample_prob = 1,
    mainland_sample_type = "undiscovered",
    replicates = 10,
    verbose = FALSE
  )
  ideal_daisie_data <- daisie_mainland_data$ideal_multi_daisie_data[[1]] # a daisie_data
  empirical_daisie_data <- daisie_mainland_data$empirical_multi_daisie_data[[1]] # a daisie_data
```

Plot each of these using `plot_daisie_data`

**Comment by joshwlambert** [comment]
@richelbilderbeek given the function `format_to_data_data` is not longer in the package, that we stop development of plot_daisie_data. What do you think?

**Comment by richelbilderbeek** [comment]
Hmmm, I am getting confused here. I understood the structure called `daisie_data` contains the info to make nice plots of the islands, for both the observed and ideal data.

What is the name of data structure I can use to plot the history of the island histories, for the observed and ideal data?

**Comment by joshwlambert** [comment]
I thought the new plan was:

* `island_tbl` to `ideal_island_tbl` and `empirical_island_tbl`
* `ideal_island_tbl` is plotted by `plot_ideal_island_tbl`
* `empirical_island_tbl` is plotted by `plot_empirical_island_tbl`

Would be the only plotting functions for the plotting the island?

**Comment by richelbilderbeek** [comment]
Hi @joshwlambert, thanks for clearing that one up!

I still would enjoy plotting the DAISIE data: it allows one to verify that the conversion from DAISIEmainland data to DAISIE has gone 

However, I will focus on plotting the `ideal_island_tbl` and `empirical_island_tbl`first (i.e. #51)

**Comment by richelbilderbeek** [comment]
This is something for after the next release. I will ruthlessly close it for now.

**Comment by richelbilderbeek** [comment]
Nope, it appears this is what #59 actually depends on; to be able to plot a `daisie_data`, so I reopen this one, as I am now working on it :-)

**Comment by richelbilderbeek** [comment]
![Screenshot from 2022-01-13 18-11-12](https://user-images.githubusercontent.com/2098230/149377201-f218ecdb-1407-4e27-aca6-55b9df6fb380.png)
![Screenshot from 2022-01-13 18-14-07](https://user-images.githubusercontent.com/2098230/149377208-8b7b2c42-bdc9-4aa7-89ed-eb61de99d739.png)

**Comment by richelbilderbeek** [comment]
Beautiful in a base-functionality-appreciated way:

![Screenshot from 2022-01-14 11-22-56](https://user-images.githubusercontent.com/2098230/149500093-0384f816-5477-42a7-8a40-ac9a8a1c2c83.png)

**Comment by richelbilderbeek** [comment]
More clades works great too:

![Screenshot from 2022-01-14 11-28-33](https://user-images.githubusercontent.com/2098230/149500959-7ae0b1ce-1998-4226-b47f-40e78b41acd5.png)

**Comment by richelbilderbeek** [comment]
An example when the two data sets differ:

![Screenshot from 2022-01-14 11-30-04](https://user-images.githubusercontent.com/2098230/149501164-3c5096ec-38d7-4a38-989a-9bc595206e55.png)


```r
test_that("much branching", {
  set.seed(
    1018,
    kind = "Mersenne-Twister",
    normal.kind = "Inversion",
    sample.kind = "Rejection"
  )
  daisie_mainland_data <- sim_island_with_mainland(
    total_time = 1,
    m = 10,
    island_pars = c(1, 1, 10, 0.1, 1),
    mainland_ex = 1,
    mainland_sample_prob = 1,
    mainland_sample_type = "complete",
    replicates = 1,
    verbose = FALSE
  )
  plot_daisie_mainland_data(daisie_mainland_data, replicate_index = 1)
})
```
