### ISSUE TITLE
Remove link to Tidyverse coding standard?

### ISSUE THREAD

**Issue by richelbilderbeek** [joshwlambert/DAISIEmainland#48]
I've added some code that ends with:

```r
some_function_name <- function(...) {
  # ...

  # See https://style.tidyverse.org/functions.html#return
  invisible(return_type)
}
```

@joshwlambert do you agree to follow the Tidyverse recommendations here? 

If yes, I will happily remove the comments linking to the Tidyverse style guide :-)

**Comment by joshwlambert** [comment]
Fixed will close when merged to main.
