### ISSUE TITLE
Write function to create `ideal_island_tbl` and `emperical_island_tbl` from `island_tbl`

### ISSUE THREAD

**Issue by richelbilderbeek** [joshwlambert/DAISIEmainland#55]
Currently, `plot_island_tbl` works on an `island_table`, where the `island_table` does not yet separate for an omniscient/emperical observer. As far as I understand (see email exchange below), this is possible.

## Email

From me: @richelbilderbeek 

> I was working on `plot_island`.
>
>I feel I miss quite some information: where are the empirical and ideal data used by `plot_island_tbl`? `sim_island` used to return both. What do I overlook here?

From @joshwlambert:

> The island_tbl is lower level than the ideal and empirical data. island_tbl is produced by sim_island and then the island_tbl is passed to create_daisie_data where the ideal and empirical data is created [...]

> I just thought about the issue and I think it's not trivial. Ideally we would want to be able to plot the ideal and empirical data, but this is not available in the island_tbl and we want to use the information from island_tbl as this contains more information than the ideal and empirical data. Therefore I suggest we write a new function that is specifically designed to take the island_tbl and create an ideal_island_tbl and empirical_island_tbl that can be used specifically for plotting. What do you think?

**Comment by richelbilderbeek** [comment]
Maybe this is not in the coming release, but let's assign @joshwlambert as he knows how to split that data :-)

**Comment by joshwlambert** [comment]
@richelbilderbeek would you like me to write the functions to produce ideal_island_tbl and empirical_island_tbl?

**Comment by richelbilderbeek** [comment]
Hi @joshwlambert, definitely I'd prefer you to do it, as (1) you've done it before, (2) I have no ideas how you did it.

AFAICS, there is no rush (we focus on `plot_island_tbl` now), but I'd love to have it one day :-)

**Comment by joshwlambert** [comment]
Sure, happy to work on it. @richelbilderbeek What information should be in the `ideal_island_tbl` and `empirical_island_tbl`, the same as `island_tbl` or additional information to help with plotting?

**Comment by richelbilderbeek** [comment]
Great! I only need to have all the info in a not-too-obscure way, e.g. similar to `island_tbl` is fine [1]. 

 * [1] I do miss the clades that went extinct in `island_tbl`, but we'll talk about that after the next release :-)

**Comment by joshwlambert** [comment]
Change of plans means these function are not going to be needed.
