### ISSUE TITLE
Use time before present + plot recolonisations

### ISSUE THREAD

**Issue by joshwlambert** [joshwlambert/DAISIEmainland#62]
The `Endemic_singleton_MaxAge` island species are plotted near the edge of the plot but they should have the longest line. This makes me think that the `plot_daisie_mainland_data` function should plot "Time before present" on the x-axis. @richelbilderbeek would this be possible for you to implement?

**Comment by joshwlambert** [comment]
Minimal working example:

set.seed(
  1,
  kind = "Mersenne-Twister",
  normal.kind = "Inversion",
  sample.kind = "Rejection"
)

daisie_mainland_data <- DAISIEmainland::sim_island_with_mainland(
  total_time = 1,
  m = 100,
  island_pars = c(1.0, 0.5, 10, 0.1, 0.5),
  mainland_ex = 2,
  mainland_sample_prob = 1,
  mainland_sample_type = "complete",
  replicates = 1,
  verbose = FALSE
)

DAISIEmainland::plot_daisie_mainland_data(
  daisie_mainland_data = daisie_mainland_data,
  replicate_index = 1
)

**Comment by joshwlambert** [comment]
![image](https://user-images.githubusercontent.com/46606402/149974457-6dba3349-85f6-4cf4-9c08-92f3e806f372.png)

**Comment by joshwlambert** [comment]
Potentially a second bug in `plot_daisie_mainland_data`. In this example the ideal data should plot a recolonisation, but only plots one of the species from the `all_colonisations`. 

set.seed(
  1,
  kind = "Mersenne-Twister",
  normal.kind = "Inversion",
  sample.kind = "Rejection"
)

daisie_mainland_data <- DAISIEmainland::sim_island_with_mainland(
  total_time = 1,
  m = 50,
  island_pars = c(1.0, 0.5, 10, 0.1, 0.5),
  mainland_ex = 2,
  mainland_sample_prob = 1,
  mainland_sample_type = "complete",
  replicates = 1,
  verbose = FALSE
)

DAISIEmainland::plot_daisie_mainland_data(
  daisie_mainland_data = daisie_mainland_data,
  replicate_index = 1
)

**Comment by joshwlambert** [comment]
![image](https://user-images.githubusercontent.com/46606402/149987860-c49404d7-f8ce-499e-93fc-23feeaca6bd7.png)

**Comment by richelbilderbeek** [comment]
@joshwlambert thanks for the bug reports! I will fix this tonight.

**Comment by richelbilderbeek** [comment]
Moved the first part of the Isse to #64.

**Comment by richelbilderbeek** [comment]
* First part of the Issue is at #64
 * Second part of the Issue is at #68

Hence, this can be closed :-)
