### ISSUE TITLE
Plot all recolonisations in 'plot_daisie_mainland_data'

### ISSUE THREAD

**Issue by richelbilderbeek** [joshwlambert/DAISIEmainland#68]
From [Issue 62 here](https://github.com/joshwlambert/DAISIEmainland/issues/62#issuecomment-1015645529) I quote:

[...] In this example the ideal data should plot a recolonisation, but only plots one of the species from the all_colonisations.

```r
set.seed(
  1,
  kind = "Mersenne-Twister",
  normal.kind = "Inversion",
  sample.kind = "Rejection"
)

daisie_mainland_data <- DAISIEmainland::sim_island_with_mainland(
  total_time = 1,
  m = 50,
  island_pars = c(1.0, 0.5, 10, 0.1, 0.5),
  mainland_ex = 2,
  mainland_sample_prob = 1,
  mainland_sample_type = "complete",
  replicates = 1,
  verbose = FALSE
)

DAISIEmainland::plot_daisie_mainland_data(
  daisie_mainland_data = daisie_mainland_data,
  replicate_index = 1
)
```

![image](https://user-images.githubusercontent.com/46606402/149987860-c49404d7-f8ce-499e-93fc-23feeaca6bd7.png)

**Comment by richelbilderbeek** [comment]
So, this is how the plot looks like, after fixing #64:

![Screenshot from 2022-01-24 18-52-52](https://user-images.githubusercontent.com/2098230/150837327-b54bce54-ba2a-4684-b097-231f95509242.png)

**Comment by richelbilderbeek** [comment]
The first notes:

![Screenshot from 2022-01-24 18-58-04](https://user-images.githubusercontent.com/2098230/150838952-df02d0dc-775a-4ed6-9d77-f68dd0a55af2.png)

**Comment by richelbilderbeek** [comment]
In code:

```r
>   names(daisie_mainland_data$empirical_multi_daisie_data[[1]][[3]])
[1] "branching_times" "stac"            "missing_species"
>   names(daisie_mainland_data$ideal_multi_daisie_data[[1]][[3]])
[1] "branching_times"   "stac"              "missing_species"  
[4] "all_colonisations"
```

And:

```r
>   daisie_mainland_data$empirical_multi_daisie_data[[1]][[3]]
$branching_times
[1] 1.0000000 0.7579685 0.6003790

$stac
[1] 2

$missing_species
[1] 0
```

```r
>   daisie_mainland_data$ideal_multi_daisie_data[[1]][[3]]
$branching_times
[1] 1.000000 0.600379

$stac
[1] 3

$missing_species
[1] 0

$all_colonisations
$all_colonisations[[1]]
$all_colonisations[[1]]$event_times
[1] 1.000000 0.600379

$all_colonisations[[1]]$species_type
[1] "A"


$all_colonisations[[2]]
$all_colonisations[[2]]$event_times
[1] 1.0000000 0.1847087

$all_colonisations[[2]]$species_type
[1] "A"
```

**Comment by richelbilderbeek** [comment]
Now with some notes:

![Screenshot from 2022-01-24 19-15-12](https://user-images.githubusercontent.com/2098230/150840671-130bd546-f76a-42ba-a2fb-1dca727e6fad.png)

**Comment by richelbilderbeek** [comment]
Indeed, the recolonisation does not show up in the result of `daisie_data_to_tables`:

![Screenshot from 2022-01-24 19-49-05](https://user-images.githubusercontent.com/2098230/150845219-f02ea1cf-107c-461b-882c-744586582eff.png)

**Comment by richelbilderbeek** [comment]
![Screenshot from 2022-01-24 19-15-12](https://user-images.githubusercontent.com/2098230/150846629-68a2c8b1-24ca-4e22-bbd7-a5c76d8890ad.png)

There are two versions shown, the upper is the one-line-per-re-/-colonist, the lower is the one-line-is-beautiful setup.

@joshwlambert: am I correct that the figure above shows how it should like like? If yes, which version do you prefer?

**Comment by richelbilderbeek** [comment]
Per email, Josh picked the lower version.

**Comment by joshwlambert** [comment]
@richelbilderbeek Just to clarify, the lower version is the one line per colonist and not the recolonists plotted on the same line?

**Comment by richelbilderbeek** [comment]
@joshwlambert, happy to clarify and be checked :-)

The 'lower version' I meant is like this (I adapted the picture from above) this picture, where a clade would like like this:

![150846629-68a2c8b1-24ca-4e22-bbd7-a5c76d8890ad](https://user-images.githubusercontent.com/2098230/151024427-66a1fb97-816b-429b-96ff-b3d1aa6d81dd.png)

What happened is this clade:

 * colonisation at t = 0.6
 * re-colonisation at t = 0.2
 * no branching events

So, does the drawing match expectations?

**Comment by richelbilderbeek** [comment]
@joshwlambert well, maybe there **is** a branching event. Question is, how would you plot this DAISIE data object (it is `daisie_mainland_data$ideal_multi_daisie_data[[1]][[3]]` in the tests above):

```r
$branching_times
[1] 1.000000 0.600379

$stac
[1] 3

$missing_species
[1] 0

$all_colonisations
$all_colonisations[[1]]
$all_colonisations[[1]]$event_times
[1] 1.000000 0.600379

$all_colonisations[[1]]$species_type
[1] "A"


$all_colonisations[[2]]
$all_colonisations[[2]]$event_times
[1] 1.0000000 0.1847087

$all_colonisations[[2]]$species_type
[1] "A"
```

**Comment by joshwlambert** [comment]
@richelbilderbeek I would plot the two colonisations in the `all_colonistations` as two separate lines. The colour of which would depend on their endemicity given by the `species_type` in `all_colonisations`.

**Comment by richelbilderbeek** [comment]
@joshwlambert so this would be a good sketch?

![like_this](https://user-images.githubusercontent.com/2098230/151129297-00898d97-e4d7-424a-8aef-44f8ab02ba63.png)

**Comment by richelbilderbeek** [comment]
OK, zooming in on the problem, I added this test to `test-plot_daisie_data.R`:

```r
test_that("Issue #68: plot all recolonisations", {
  set.seed(
    1,
    kind = "Mersenne-Twister",
    normal.kind = "Inversion",
    sample.kind = "Rejection"
  )
  
  daisie_mainland_data <- DAISIEmainland::sim_island_with_mainland(
    total_time = 1,
    m = 50,
    island_pars = c(1.0, 0.5, 10, 0.1, 0.5),
    mainland_ex = 2,
    mainland_sample_prob = 1,
    mainland_sample_type = "complete",
    replicates = 1,
    verbose = FALSE
  )
  daisie_data <- daisie_mainland_data$ideal_multi_daisie_data[[1]]
  plot_daisie_data(daisie_data)
})
```

This is the problem:

![annotated](https://user-images.githubusercontent.com/2098230/151223775-4e3f8047-7a65-4fda-9d3d-6c1e9746f30f.png)

**Comment by richelbilderbeek** [comment]
Using vertical lines solves the problem is a way:

![Screenshot from 2022-01-26 19-24-28](https://user-images.githubusercontent.com/2098230/151223815-cccf34d2-847d-45e1-ab0a-1c9c921ae08a.png)

**Comment by joshwlambert** [comment]
@richelbilderbeek I have accepted the PR. Thanks for the nice plots. However, I would like the recolonists plotted as separate lines, each with their own colonisation time and not linked by any branching events. Would this be possible.

**Comment by richelbilderbeek** [comment]
@joshwlambert I think yes, as Saturday I seem to have plenty of time to fix that, as well as fixing the vertical branches being misplaced!

**Comment by richelbilderbeek** [comment]
This will be harder: the algorithm to spread out branches is one thing, doing the same for colonists, that may branch out as well, may be hard! Let's first write a solid test :angel:

**Comment by richelbilderbeek** [comment]
```
test_that("Issue #68: plot all recolonisations with many branches", {
  set.seed(
    631,
    kind = "Mersenne-Twister",
    normal.kind = "Inversion",
    sample.kind = "Rejection"
  )

  daisie_mainland_data <- DAISIEmainland::sim_island_with_mainland(
    total_time = 1,
    m = 10,
    island_pars = c(1, 1, 10, 0.1, 1),
    mainland_ex = 1,
    mainland_sample_prob = 1,
    mainland_sample_type = "complete",
    replicates = 1,
    verbose = FALSE
  )
  DAISIEmainland::plot_daisie_mainland_data(
    daisie_mainland_data = daisie_mainland_data,
    replicate_index = 1
  )
  # Plots nicely
  daisie_data <- daisie_mainland_data$ideal_multi_daisie_data[[1]]
  plot_daisie_data(daisie_data)

  # Plots nicely when there are no colonisations
  daisie_data <- daisie_mainland_data$empirical_multi_daisie_data[[1]]
  plot_daisie_data(daisie_data)
})
```

![Screenshot from 2022-02-20 19-05-28](https://user-images.githubusercontent.com/2098230/154857124-06ffedc8-3f5b-4140-ba04-f05632599396.png)

**Comment by richelbilderbeek** [comment]
OK, that one should display as:

![issue_68](https://user-images.githubusercontent.com/2098230/154860542-15a580cd-d780-4898-898a-913f68c3a8d1.png)

**Comment by richelbilderbeek** [comment]
```
Here is the best one yet:

```
test_that("Multiple recolonisations", { # nolint indeed, this is complex :-)
  skip("Only run locally")
  seed <- 1912
  set.seed(
    seed,
    kind = "Mersenne-Twister",
    normal.kind = "Inversion",
    sample.kind = "Rejection"
  )
  daisie_mainland_data <- sim_island_with_mainland(
    total_time = 1,
    m = 10,
    island_pars = c(1, 0.1, 30.0, 1.0, 5.0),
    mainland_ex = 1,
    mainland_sample_prob = 1,
    mainland_sample_type = "complete",
    replicates = 1,
    verbose = FALSE
  )
  ideal_daisie_data <- daisie_mainland_data$ideal_multi_daisie_data[[1]]
  clade_index <- 9
  n_colonisations <- length(ideal_daisie_data[[clade_index]]$all_colonisations) # nolint indeed a long line
  n_branches <- length(ideal_daisie_data[[clade_index]]$branching_times) - 1 # nolint indeed a long line
  expect_true(n_colonisations >= 3 && n_branches >= n_colonisations * 2)
  interesting_clade <- ideal_daisie_data[clade_index]
  plot_daisie_data(ideal_daisie_data)

  simplified_ideal_daisie_data <- list()
  simplified_ideal_daisie_data[[1]] <- ideal_daisie_data[[1]]
  simplified_ideal_daisie_data[[2]] <- ideal_daisie_data[[9]]
  plot_daisie_data(daisie_data = simplified_ideal_daisie_data)
})
```

with 

```
> simplified_ideal_daisie_data
[[1]]
[[1]]$island_age
[1] 1

[[1]]$not_present
[1] 5


[[2]]
[[2]]$branching_times
[1] 1.00000000 0.81360371 0.59927594 0.54433504 0.43080142 0.11137935 0.04632135

[[2]]$stac
[1] 3

[[2]]$missing_species
[1] 0

[[2]]$all_colonisations
[[2]]$all_colonisations[[1]]
[[2]]$all_colonisations[[1]]$event_times
[1] 1.0000000 0.8136037 0.5992759 0.4308014

[[2]]$all_colonisations[[1]]$species_type
[1] "C"


[[2]]$all_colonisations[[2]]
[[2]]$all_colonisations[[2]]$event_times
[1] 1.00000000 0.54433504 0.04632135

[[2]]$all_colonisations[[2]]$species_type
[1] "C"


[[2]]$all_colonisations[[3]]
[[2]]$all_colonisations[[3]]$event_times
[1] 1.0000000 0.3858606 0.1113793

[[2]]$all_colonisations[[3]]$species_type
[1] "C"
```

**Comment by richelbilderbeek** [comment]
I guess this is how it should look?

![issue_68](https://user-images.githubusercontent.com/2098230/155018477-4c6eb076-f170-4f06-868e-a5a3f55313fa.png)

**Comment by richelbilderbeek** [comment]
Getting there:

![Screenshot from 2022-03-02 16-51-09](https://user-images.githubusercontent.com/2098230/156397498-3152b2bb-2bd1-40c6-b4fc-1cbc54054bf4.png)

**Comment by richelbilderbeek** [comment]
Done! It is nearly beautiful:

![Screenshot from 2022-03-03 19-58-24](https://user-images.githubusercontent.com/2098230/156633572-8defe81f-7ac0-4868-a1fb-f7b59ca6c53c.png)
