### ISSUE TITLE
No branching for colonist that underwent anagenesis?

### ISSUE THREAD

**Issue by richelbilderbeek** [joshwlambert/DAISIEmainland#72]
Dear DAISIEmainland maintainer, hi @joshwlambert,

Thanks for DAISIEmainland and its many tests; well done!

When fixing `plot_daisie_data` I find some behavior that I did not expect. I hope you can confirm this behavior is correct.

In a scenario with one or more colonisation events, there are two types of events: cladogenesis and anagensis. Cladogenesis works exactly as expected, with more branches for a higher cladogenesis rate. 

Anagenesis, however, feels unexpected to me: it happens after which ... nothing happens anymore. I expected that  when a new species is formed due to anagenesis, that after some time also here branching/speciation/cladogenesis will take place. 

Below is some code that will stop when after anagenesis a branching event happens. It never stops: 

```r
test_that("No branching for colonist that underwent anagenesis?", { # nolint indeed, this is complex :-)
  # Issue 72, Issue #72
  skip("Only run locally")
  seed <- 0
  while (1) {
    seed <- seed + 1
    message(seed)
    set.seed(
      seed,
      kind = "Mersenne-Twister",
      normal.kind = "Inversion",
      sample.kind = "Rejection"
    )
    daisie_mainland_data <- sim_island_with_mainland(
      total_time = 1,
      m = 10,
      island_pars = c(1, 0.1, 30.0, 1.0, 5.0),
      mainland_ex = 1,
      mainland_sample_prob = 1,
      mainland_sample_type = "complete",
      replicates = 1,
      verbose = FALSE
    )
    ideal_daisie_data <- daisie_mainland_data$ideal_multi_daisie_data[[1]]
    if (length(ideal_daisie_data) == 1) next
    for (clade_index in seq(2, length(ideal_daisie_data))) {
      n_colonisations <- length(ideal_daisie_data[[clade_index]]$all_colonisations) # nolint indeed a long line
      if (n_colonisations == 0) next
      for (colonist_index in seq(1, n_colonisations))
      {
        colonisation <- ideal_daisie_data[[clade_index]]$all_colonisations[[colonist_index]]
        if (colonisation$species_type == "A") {
          message(
            "{",
            paste0(colonisation$event_times, collapse = ", "), "}, ",
            colonisation$species_type
          )
        }
        if (colonisation$species_type == "A" && length(colonisation$event_times) > 2) {
          stop("IT HAPPENS")
        }
      }
    }
  }
})
```

Part of the output, which show either a seed (e.g. the first 3878 is a seed), after which it shows the `event_times` for colonists of type `A`:

```
3878
{1, 0.965882442575452}, A
3879
3880
3881
{1, 0.624526011509188}, A
3882
3883
{1, 0.560925557743758}, A
3884
{1, 0.753004678780446}, A
3885
{1, 0.380113761534661}, A
3886
{1, 0.926155241206288}, A
{1, 0.425706043460982}, A
3887
3888
3889
{1, 0.306620127055545}, A
3890
{1, 0.424082266123013}, A
3891
{1, 0.797596911233376}, A
3892
{1, 0.857255430271893}, A
{1, 0.399581177773567}, A
{1, 0.103363494543277}, A
{1, 0.826918459497392}, A
3893
3894
```

Is the behavior -that after anagenesis there are no more branching events- correct?

Thanks and cheers, Richel

**Comment by joshwlambert** [comment]
@richelbilderbeek I believe this is due to the output of `sim_island_with_mainland()` being reconstructed (i.e. we do not have the full information of all the extinct lineages, only those that survive to the present) and so there may have been branching events in this lineage but these were followed by an extinction or that these lineages never underwent cladogenesis after anagenesis. It should not be the case that anagenesis prevents in these lineages. I will also check the code to make sure that this is not happening.

**Comment by richelbilderbeek** [comment]
Is correct!
