### ISSUE TITLE
Numerical integrator use

### ISSUE THREAD

**Issue by Neves-P** [joshwlambert/DAISIEmainland#74]
The long form documentation points to the use of RKF78 as the numerical integrator, yet DAISIE v4.1.1 uses lsodes as default. Should this be changed to match DAISIE?

See here: https://joshwlambert.github.io/DAISIEmainland/inference-performance.html#maximum-likelihood-inference

> The details of the maximum likelihood set up are not important, but a brief explainer: all model parameters are optimisied with the starting position in parameter space for optimisation, equal to the values used to simulate the data; **the Runge-Kutta Fehlberg method to numerically solve the likelihood equations**; and simplex is the optimisation algorithm to maximise the likelihood.

emphasis mine.

**Comment by joshwlambert** [comment]
RKF78 was used for all analyses and is explicitly stated as the `methode` argument throughout. Other people can change these settings if they wish, but let's leave as is for the documentation for consistency.
