### ISSUE TITLE
Suggest: remove or activate skipped tests

### ISSUE THREAD

**Issue by richelbilderbeek** [joshwlambert/DAISIEmainland#8]
Dear DAISIEmainland maintainer,

Thanks for DAISIEmainland and -among others- the proof it works correct by writing tests to achieve an awesome code coverage! However, when I search the package for the word `skip` I find 13 instances where a test is skipped. It makes me wonder if those tests should be actually run or be removed?

I suggest to either remove the `skip` or remove the test, to remove this confusion.

I do have an idea about some `skip`s why these are there: these take too long (and we know devs have an attention span of 10 secs)! Tricks I use to workaround this are (1) only run those tests on a Continuous Intrgration service ([example from babette here](https://github.com/ropensci/babette/blob/master/tests/testthat/test-bbt_run_from_model.R#L206)), or (2) simplify the test (e.g. use 3 instead of 1000 replicates).

**Comment by joshwlambert** [comment]
All previously skipped and empty tests have now been written. Sadly the style test has been removed as it would have taken too long to re-write code to reduce cyclomatic complexity, etc. and make all the code conform, as sad as this is, life is not perfect and we move on. The package has been linted locally and there are only a few faults.
