### ISSUE TITLE
CRAN disallows installing GitHub repos from vignettes

### ISSUE THREAD

**Issue by richelbilderbeek** [joshwlambert/DAISIEmainland#9]
Dear DAISIEmainland maintainer,

Thanks for DAISIEmainland and a vignette that demonstrates part of its workings!

I did spot a CRAN violation in the vignette and I suggest to fix it (which is easy). In the vignette it states:

    ```{r install dependencies}
    remotes::install_github("rsetienne/DAISIE")
    remotes::install_github("thijsjanzen/nLTT")
    remotes::install_github("joshwlambert/DAISIEmainland")
    ```

I do enjoy the helpfulness towards the users in this, but it is against CRAN policies to modify the local environment of the user (in this case, the installed packages on his/her harddisk), probably for good reasons.

I suggest to move these lines to the README.md instead.

**Comment by joshwlambert** [comment]
This has been resolved and will be closed when merged to main

**Comment by joshwlambert** [comment]
Merged to main.
